### ISSUE TITLE
Weight Chart 67.7 value look higher that 68.1

### ISSUE THREAD

**Issue by stephen775** [rcpch/digital-growth-charts-documentation#46]
![67_7_KG](https://user-images.githubusercontent.com/26459953/163975239-2e7be7f7-2560-4080-b302-c1f5b2bb340b.png)
![68_1_KG](https://user-images.githubusercontent.com/26459953/163975235-e7aad051-5c4d-4109-a18a-a88fb4c18a81.png)
![fullchart](https://user-images.githubusercontent.com/26459953/163975240-198b662c-e3cd-48f5-8b0d-ecf08ea97f50.png)

Hi,
This was noticed by one of the clinicians.

In the Down weight chart we have 5 weight observations.

Two of those observations are for a weight of 67.7 and 68.1.

Now in the chart the 67.7 look slightly higher that the 68.1 (see attached images).

Not a major issue/but is noticeable in the chart.

Thanks
Stephen

**Comment by pacharanero** [comment]
Hi Stephen,

Thanks for reporting the issue.
I think it may be an optical illusion actually, caused by the curvature of
the centile lines of the background.

![image](https://user-images.githubusercontent.com/2348385/163978564-66b0dbb3-218f-4fb8-a3fd-46afb3ca4082.png)

If I have understood the issue right it was that the 67.7 appeared to be
higher than the 68.1 - as you can see with these horizontal lines added the
68.1 is definitely the higher of the two, although it looks different in
the view that doesn't have the blue tooltip overlay - I can certainly see
the illusion that makes it look higher.

Let me know if this helps or if I've got the issue wrong.

Marcus

**Comment by pacharanero** [comment]
![image](https://user-images.githubusercontent.com/2348385/163978805-51e68e80-73ca-421d-8f93-6380d673e0de.png)

**Comment by eatyourpeas** [comment]
@pacharanero illustrates it nicely. Just to add the newer charts are 6.0.1 (though may have some breaking changes on the version you have) - with the newer version you get SDS scores as well in then tool tip, and copy and paste and SDS charts amongst other things.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1058647/163982572-bbbb281e-357f-402a-8a66-ba15e1ee7a21.png">
